project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
    - assets/hero-imaging.png

website:
  title: "Teppei Kurita"
  site-url: "https://tkuri.github.io/"
  navbar: false
  page-footer:
    center: "Copyright 2026 Teppei Kurita. The views expressed on this site are my own and do not necessarily reflect those of my employer."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    smooth-scroll: true
    link-external-newwindow: true
